/**
 * Twine
 * Twine server REST Api definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gokmen@goksel.me
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Twine) {
      root.Twine = {};
    }
    root.Twine.OK = factory(root.Twine.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OK model module.
   * @module model/OK
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OK</code>.
   * @alias module:model/OK
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>OK</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OK} obj Optional instance to populate.
   * @return {module:model/OK} The populated <code>OK</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ok')) {
        obj['ok'] = ApiClient.convertToType(data['ok'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} ok
   * @default true
   */
  exports.prototype['ok'] = true;



  return exports;
}));


